apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xn1asrjmn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xn1asrjmn-python 
  name: xn1asrjmn-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xn1asrjmn-python 
